# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Save-Your' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'

  # Pods for senior_design_2019

  target 'Save-YourTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Save-YourUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
